/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/model/cubes_mesh_simple.glb') as any;
  const bgTexture = useTexture('/model/overlapping_cubes.png');
  bgTexture.flipY = false;
  const centerTexture = useTexture('/model/cubes_center_2048.jpg');
  centerTexture.flipY = false;

  return (
    <group {...props} dispose={null} scale={2.5}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
      >
        <meshBasicMaterial map={bgTexture} />
      </mesh>
      <mesh geometry={nodes.Center.geometry}>
        <meshBasicMaterial map={centerTexture} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/model/cubes_mesh_simple.glb');
