/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/model/cubes_mesh_simple.glb') as any;
  const bakedTexture = useTexture('/model/cubes_simple_2048.jpg');
  bakedTexture.flipY = false;

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI / 4, 0]} scale={2.5}>
      <mesh
        castShadow
        receiveShadow
        // material={materials.Material}
        geometry={nodes.Plane.geometry}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/model/cubes_mesh_simple.glb');
