/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export function Background(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/Background.glb') as any;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[0, 0.5, 0]}
      />
      <mesh
        geometry={nodes.CubeGenerator001_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[0, 0.5, 0]}
      />
    </group>
  );
}

useGLTF.preload('/livingRoom.glb');
