/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export function BGCenter(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/model/BGCenter.glb') as any;
  const texture = useTexture('/model/BGCenter.png');
  texture.flipY = false;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.CubeGenerator002_Baked.geometry}
        position={[0, 0.5, 0]}
      >
        <meshBasicMaterial map={texture} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/model/BGCenter.glb');
