/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { Float, useGLTF } from '@react-three/drei';

export function FloatingCube(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/FloatingCube.glb') as any;
  return (
    <group {...props} dispose={null}>
      <Float
        {...props}
        speed={1} // Animation speed, defaults to 1
        rotationIntensity={1} // XYZ rotation intensity, defaults to 1
        floatIntensity={1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
        floatingRange={[-0.1, 0.1]} // Range of y-axis values the object will float within, defaults to [-0.1,0.1]
      >
        <mesh
          geometry={nodes.Cube_Baked.geometry}
          material={materials.FloatingCube_Baked}
        />
      </Float>
      {/* <Box scale={0.5} /> */}
      <mesh
        geometry={nodes.Instance_Baked.geometry}
        material={materials.FloatingCube_Baked}
      />
    </group>
  );
}

useGLTF.preload('/model/FloatingCube.glb');
