/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Hogwarts(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/Hogwarts.glb') as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Quad_Baked.geometry}
        material={materials.Hogwarts_Baked}
      />
      <mesh
        geometry={nodes.HogBG_Baked.geometry}
        material={materials.Hogwarts_Baked}
      />
    </group>
  );
}

useGLTF.preload('/model/Hogwarts.glb');
