/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Landing(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/Landing.glb') as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.BG001_Baked.geometry}
        material={materials.Landing_Baked}
      />
    </group>
  );
}

useGLTF.preload('/model/Landing.glb');
