/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { Annotation } from '../components/Annotation';

export function LivingRoom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/livingRoom.glb') as any;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.TV_Baked.geometry}
        material={materials.livingRoom_Baked}
      />
      <mesh
        geometry={nodes.Xbox_Baked.geometry}
        material={materials.livingRoom_Baked}
      >
        <Annotation position={[0, 0.35, -0.49]} scale={0.25}>This is an XBox</Annotation>
      </mesh>
      <mesh
        geometry={nodes.Sofa_Baked.geometry}
        material={materials.livingRoom_Baked}
      />
      <mesh
        geometry={nodes.TV_Cabinet_Baked.geometry}
        material={materials.livingRoom_Baked}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Walls_Baked.geometry}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Door_Baked.geometry}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Planks_Baked.geometry}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Foundation_Baked.geometry}
      />
    </group>
  );
}

useGLTF.preload('/livingRoom.glb');
