/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { Annotation } from '../components/Annotation';

export function LivingRoom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/livingRoom.glb') as any;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.TV_Baked.geometry}
        material={materials.livingRoom_Baked}
      />
      <mesh
        geometry={nodes.Xbox_Baked.geometry}
        material={materials.livingRoom_Baked}
      >
        <Annotation position={[-1, 0.5, -0.49]} scale={0.25}>
          <h2>Sky</h2>
          <h3>September 2018 - Present</h3>
          <sub>Frontend Developer</sub>
          <section>
            <h4>Sky Q - Sky X</h4>
            <p>
              A multi-screen, multi-proposition, multi-territory SmartTV app to
              access Sky content.
            </p>
          </section>
          <section>
            <h4>Peacock - SkyShowtime - Showmax</h4>
            <p>
              A fully featured streaming application. Worked on the SmartTV,
              Console and STB clients.
            </p>
          </section>
        </Annotation>
      </mesh>
      <mesh
        geometry={nodes.Sofa_Baked.geometry}
        material={materials.livingRoom_Baked}
      />
      <mesh
        geometry={nodes.TV_Cabinet_Baked.geometry}
        material={materials.livingRoom_Baked}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Walls_Baked.geometry}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Door_Baked.geometry}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Planks_Baked.geometry}
      />
      <mesh
        material={materials.livingRoom_Baked}
        geometry={nodes.Foundation_Baked.geometry}
      />
    </group>
  );
}

useGLTF.preload('/livingRoom.glb');
