/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Office(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/Office.glb') as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Desk001_Baked"
        geometry={nodes.Desk001_Baked.geometry}
        material={materials.Office_Baked}
        position={[0.5, 0, 0]}
      />
      <mesh
        name="Desk_Baked"
        geometry={nodes.Desk_Baked.geometry}
        material={materials.Office_Baked}
        position={[0, 0, 0.5]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Door001_Baked"
        geometry={nodes.Door001_Baked.geometry}
        material={materials.Office_Baked}
        position={[-0.203, 0, 0]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Foundation001_Baked"
        geometry={nodes.Foundation001_Baked.geometry}
        material={materials.Office_Baked}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Planks001_Baked"
        geometry={nodes.Planks001_Baked.geometry}
        material={materials.Office_Baked}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Walls001_Baked"
        geometry={nodes.Walls001_Baked.geometry}
        material={materials.Office_Baked}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
    </group>
  );
}

useGLTF.preload('/model/Office.glb');
