/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useMemo, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { MathUtils, ShaderMaterial, TextureLoader } from 'three';
import { useFrame, useLoader } from '@react-three/fiber';
import { DefaultVertex, TextureMixFragment } from '../materials/TextureMix';

export function Office(
  props: JSX.IntrinsicElements['group'] & { isDarkMode?: boolean },
) {
  const { nodes } = useGLTF('/model/Office.glb') as any;

  const nightTexture = useLoader(TextureLoader, '/model/Office_Night.png');
  nightTexture.flipY = false;
  const dayTexture = useLoader(TextureLoader, '/model/Office_Day.png');
  dayTexture.flipY = false;

  const [mix, setMix] = useState(props.isDarkMode ? 1 : 0);

  useFrame(() => {
    if ((props.isDarkMode && mix !== 1) || (!props.isDarkMode && mix !== 0)) {
      setMix(MathUtils.lerp(mix, props.isDarkMode ? 1 : 0, 0.05));
    }
  });

  const material = useMemo(
    () =>
      new ShaderMaterial({
        uniforms: {
          textureA: { value: dayTexture as THREE.Texture },
          textureB: { value: nightTexture as THREE.Texture },
          mixWeight: { value: mix },
        },
        vertexShader: DefaultVertex,
        fragmentShader: TextureMixFragment,
      }),
    [mix],
  );

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Desk001.geometry}
        material={material}
        position={[0.5, 0, 0]}
      />
      <mesh
        geometry={nodes.Desk.geometry}
        material={material}
        position={[0, 0, 0.5]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Door001.geometry}
        material={material}
        position={[-0.203, 0, 0]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Foundation001.geometry}
        material={material}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Planks001.geometry}
        material={material}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Desk_drawer.geometry}
        material={material}
        position={[0.439, 0.318, -0.086]}
        scale={[1.148, 0.674, 2.005]}
      />
      <mesh
        geometry={nodes.Monitor.geometry}
        material={material}
        position={[0.368, 0.412, 0.24]}
      />
      <mesh geometry={nodes.Monitor_Arm.geometry} material={material} />
      <mesh
        geometry={nodes.Walls001.geometry}
        material={material}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
    </group>
  );
}

useGLTF.preload('/model/Office.glb');
