/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useMemo, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { MathUtils, ShaderMaterial, TextureLoader } from 'three';
import { useFrame, useLoader } from '@react-three/fiber';
import { DefaultVertex, TextureMixFragment } from '../materials/TextureMix';

export function Office(
  props: JSX.IntrinsicElements['group'] & { isDarkMode?: boolean },
) {
  const { nodes, materials } = useGLTF('/model/Office.glb') as any;

  const nightTexture = useLoader(TextureLoader, '/model/Office_Night.png');
  nightTexture.flipY = false;
  const dayTexture = useLoader(TextureLoader, '/model/Office_Day.png');
  dayTexture.flipY = false;

  const [mix, setMix] = useState(props.isDarkMode ? 1 : 0);

  useFrame(() => {
    if ((props.isDarkMode && mix !== 1) || (!props.isDarkMode && mix !== 0)) {
      setMix(MathUtils.lerp(mix, props.isDarkMode ? 1 : 0, 0.05));
    }
  });

  const material = useMemo(
    () =>
      new ShaderMaterial({
        uniforms: {
          textureA: { value: dayTexture as THREE.Texture },
          textureB: { value: nightTexture as THREE.Texture },
          mixWeight: { value: mix },
        },
        vertexShader: DefaultVertex,
        fragmentShader: TextureMixFragment,
      }),
    [mix],
  );

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Desk001_Baked"
        geometry={nodes.Desk001_Baked.geometry}
        material={material}
        position={[0.5, 0, 0]}
      />
      <mesh
        name="Desk_Baked"
        geometry={nodes.Desk_Baked.geometry}
        material={material}
        position={[0, 0, 0.5]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Door001_Baked"
        geometry={nodes.Door001_Baked.geometry}
        material={material}
        position={[-0.203, 0, 0]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Foundation001_Baked"
        geometry={nodes.Foundation001_Baked.geometry}
        material={material}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Planks001_Baked"
        geometry={nodes.Planks001_Baked.geometry}
        material={material}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
      <mesh
        name="Walls001_Baked"
        geometry={nodes.Walls001_Baked.geometry}
        material={material}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={-1}
      />
    </group>
  );
}

useGLTF.preload('/model/Office.glb');
